from __future__ import annotations

import tcod

from pyrl.constants.colors import Color
from pyrl.constants.keys import Key

libtcod_color_map = {
    Color.Red:           tcod.Color(175, 0, 0),
    Color.Green:         tcod.Color(0, 175, 0),
    Color.Blue:          tcod.Color(0, 0, 175),
    Color.Purple:        tcod.Color(175, 0, 175),
    Color.Cyan:          tcod.Color(0, 175, 175),
    Color.Yellow:        tcod.Color(255, 255, 95),
    Color.Brown:         tcod.Color(150, 75, 0),
    Color.Dark_Blue:     tcod.Color(0, 0, 175),
    Color.Dark_Brown:    tcod.Color(135, 95, 0),
    Color.Light_Red:     tcod.Color(255, 95, 95),
    Color.Light_Green:   tcod.Color(95, 255, 95),
    Color.Light_Blue:    tcod.Color(95, 95, 255),
    Color.Light_Purple:  tcod.Color(255, 95, 255),
    Color.Light_Cyan:    tcod.Color(95, 255, 255),
    Color.White:         tcod.Color(255, 255, 255),
    Color.Light:         tcod.Color(218, 218, 218),
    Color.Normal:        tcod.Color(187, 187, 187),
    Color.Light_Gray:    tcod.Color(168, 168, 168),
    Color.Gray:          tcod.Color(138, 138, 138),
    Color.Dark_Gray:     tcod.Color(108, 108, 108),
    Color.Dark:          tcod.Color(78, 78, 78),
    Color.Darker:        tcod.Color(48, 48, 48),
    Color.Darkest:       tcod.Color(20, 20, 20),
    Color.Black:         tcod.Color(0, 0, 0),
}

libtcod_key_map = {
    tcod.KEY_BACKSPACE:  Key.BACKSPACE,
    tcod.KEY_DELETE:     Key.DELETE,
    tcod.KEY_DOWN:       Key.DOWN,
    tcod.KEY_END:        Key.END,
    tcod.KEY_ENTER:      Key.ENTER,
    tcod.KEY_ESCAPE:     Key.ESC,
    tcod.KEY_F1:         Key.F1,
    tcod.KEY_F2:         Key.F2,
    tcod.KEY_F3:         Key.F3,
    tcod.KEY_F4:         Key.F4,
    tcod.KEY_F5:         Key.F5,
    tcod.KEY_F6:         Key.F6,
    tcod.KEY_F7:         Key.F7,
    tcod.KEY_F8:         Key.F8,
    tcod.KEY_F9:         Key.F9,
    tcod.KEY_F10:        Key.F10,
    tcod.KEY_F11:        Key.F11,
    tcod.KEY_F12:        Key.F12,
    tcod.KEY_HOME:       Key.HOME,
    tcod.KEY_INSERT:     Key.INSERT,
    tcod.KEY_KP0:        Key.NUMPAD_0,
    tcod.KEY_KP1:        Key.NUMPAD_1,
    tcod.KEY_KP2:        Key.NUMPAD_2,
    tcod.KEY_KP3:        Key.NUMPAD_3,
    tcod.KEY_KP4:        Key.NUMPAD_4,
    tcod.KEY_KP5:        Key.NUMPAD_5,
    tcod.KEY_KP6:        Key.NUMPAD_6,
    tcod.KEY_KP7:        Key.NUMPAD_7,
    tcod.KEY_KP8:        Key.NUMPAD_8,
    tcod.KEY_KP9:        Key.NUMPAD_9,
    tcod.KEY_LEFT:       Key.LEFT,
    tcod.KEY_NONE:       Key.NO_INPUT,
    tcod.KEY_PAGEDOWN:   Key.PAGE_DOWN,
    tcod.KEY_PAGEUP:     Key.PAGE_UP,
    tcod.KEY_RIGHT:      Key.RIGHT,
    tcod.KEY_SPACE:      Key.SPACE,
    tcod.KEY_TAB:        Key.TAB,
    tcod.KEY_UP:         Key.UP,
}
