#!/bin/bash

if [ $# -eq 0 ]; then
    ./pyrl.py 2> errors.err
else
    $@ 2> errors.err
fi

if [ -s errors.err ]; then
    if [ $# -eq 0 ]; then
        vim -q errors.err
        rm errors.err
    else
        cat errors.err
    fi
else
    rm errors.err
fi
