#!/bin/bash

if [ $# -eq 0 ]; then
    ./pyrl.py 2> data/errors.err
else
    $@ 2> data/errors.err
fi

if [ -s data/errors.err ]; then
    if [ $# -eq 0 ]; then
        vim -q data/errors.err
        rm data/errors.err
    else
        cat data/errors.err
    fi
else
    rm data/errors.err
fi
