#!/bin/bash

if [ $# -eq 0 ]; then
	./pyrl.py 2> errors.err
else
	./$1 2> errors.err
fi

if [ -s errors.err ]; then
	if [ $# -eq 2 ]; then
		cat errors.err
	else
		vim -q errors.err
		rm errors.err
	fi
else
	rm errors.err
fi
