#!/usr/bin/env python

from curses import wrapper
from cPickle import load

def main(w):
	import io
	import tile

	f = open("data", "r")
	io.io = io.IO(w)
	tile.tiles = load(f)
	f.close()
	from editor import Editor
	Editor().ui()

wrapper(main)
