BASE_GREY = "COLOR_GREY"
BASE_BLACK = "COLOR_FULL_BLACK"
BASE_RED = "COLOR_RED"
BASE_GREEN = "COLOR_GREEN"
BASE_BROWN = "COLOR_BROWN"
BASE_BLUE = "COLOR_BLUE"
BASE_PURPLE = "COLOR_PURPLE"
BASE_CYAN = "COLOR_CYAN"

BASE_WHITE = "COLOR_WHITE"
BASE_DARK = "COLOR_DARK_BLACK"
BASE_LIGHT_RED = "COLOR_LIGHT_RED"
BASE_LIGHT_GREEN = "COLOR_LIGHT_GREEN"
BASE_YELLOW = "COLOR_YELLOW"
BASE_LIGHT_BLUE = "COLOR_LIGHT_BLUE"
BASE_LIGHT_PURPLE = "COLOR_LIGHT_PURPLE"
BASE_LIGHT_CYAN = "COLOR_LIGHT_CYAN"

NORMAL = (BASE_GREY, BASE_BLACK)

GREY = (BASE_GREY, BASE_BLACK)
BLACK = (BASE_BLACK, BASE_BLACK)
RED = (BASE_RED, BASE_BLACK)
GREEN = (BASE_GREEN, BASE_BLACK)
BROWN = (BASE_BROWN, BASE_BLACK)
BLUE = (BASE_BLUE, BASE_BLACK)
PURPLE = (BASE_PURPLE, BASE_BLACK)
CYAN = (BASE_CYAN, BASE_BLACK)

WHITE = (BASE_WHITE, BASE_BLACK)
DARK = (BASE_DARK, BASE_BLACK)
LIGHT_RED = (BASE_LIGHT_RED, BASE_BLACK)
LIGHT_GREEN = (BASE_LIGHT_GREEN, BASE_BLACK)
YELLOW = (BASE_YELLOW, BASE_BLACK)
LIGHT_BLUE = (BASE_LIGHT_BLUE, BASE_BLACK)
LIGHT_PURPLE = (BASE_LIGHT_PURPLE, BASE_BLACK)
LIGHT_CYAN = (BASE_LIGHT_CYAN, BASE_BLACK)
