BLACK_ON_BLACK = u"black_on_black"
BROWN = u"brown"
GRAY = u"gray"
RED = u"red"
GREEN = u"green"
YELLOW = u"yellow"
BLUE = u"blue"
PURPLE = u"purple"
CYAN = u"cyan"
WHITE = u"white"
BLACK = u"black"
LIGHT_RED = u"light_red"
LIGHT_GREEN = u"light_green"
LIGHT_YELLOW = u"light_yellow"
LIGHT_BLUE = u"light_blue"
LIGHT_PURPLE = u"light_purple"
LIGHT_CYAN = u"light_cyan"

NORMAL = u"normal"
BLINK = u"blink"
BOLD = u"bold"
DIM = u"dim"
REVERSE = u"reverse"
STANDOUT = u"standout"
UNDERLINE = u"underline"

MAKE_REVERSE = u"r"
