from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

BASE_RED = "COLOR_RED"
BASE_GREEN = "COLOR_GREEN"
BASE_BLUE = "COLOR_BLUE"
BASE_PURPLE = "COLOR_PURPLE"
BASE_CYAN = "COLOR_CYAN"
BASE_YELLOW = "COLOR_YELLOW"
BASE_BROWN = "COLOR_BROWN"

BASE_DARK_BLUE = "COLOR_DARK_BLUE"
BASE_DARK_BROWN = "COLOR_DARK_BROWN"

BASE_LIGHT_RED = "COLOR_LIGHT_RED"
BASE_LIGHT_GREEN = "COLOR_LIGHT_GREEN"
BASE_LIGHT_BLUE = "COLOR_LIGHT_BLUE"
BASE_LIGHT_PURPLE = "COLOR_LIGHT_PURPLE"
BASE_LIGHT_CYAN = "COLOR_LIGHT_CYAN"

BASE_WHITE = "COLOR_WHITE"  # 255
BASE_LIGHT = "COLOR_LIGHT"  # 218
BASE_NORMAL = "COLOR_NORMAL"  # 187
BASE_LIGHT_GRAY = "COLOR_LIGHT_GRAY"  # 168
BASE_GRAY = "COLOR_GRAY"  # 138
BASE_DARK_GRAY = "COLOR_DARK_GRAY"  # 108
BASE_DARK = "COLOR_DARK"  # 78
BASE_DARKER = "COLOR_DARKER"  # 48
BASE_DARKEST = "COLOR_DARKEST"  # 18
BASE_BLACK = "COLOR_BLACK"  # 0

RED = (BASE_RED, BASE_BLACK)
GREEN = (BASE_GREEN, BASE_BLACK)
BLUE = (BASE_BLUE, BASE_BLACK)
PURPLE = (BASE_PURPLE, BASE_BLACK)
CYAN = (BASE_CYAN, BASE_BLACK)
YELLOW = (BASE_YELLOW, BASE_BLACK)
BROWN = (BASE_BROWN, BASE_BLACK)

DARK_BLUE = (BASE_DARK_BLUE, BASE_BLACK)
DARK_BROWN = (BASE_DARK_BROWN, BASE_BLACK)

LIGHT_RED = (BASE_LIGHT_RED, BASE_BLACK)
LIGHT_GREEN = (BASE_LIGHT_GREEN, BASE_BLACK)
LIGHT_BLUE = (BASE_LIGHT_BLUE, BASE_BLACK)
LIGHT_PURPLE = (BASE_LIGHT_PURPLE, BASE_BLACK)
LIGHT_CYAN = (BASE_LIGHT_CYAN, BASE_BLACK)

WHITE = (BASE_WHITE, BASE_BLACK)
LIGHT = (BASE_LIGHT, BASE_BLACK)
NORMAL = (BASE_NORMAL, BASE_BLACK)
LIGHT_GRAY = (BASE_LIGHT_GRAY, BASE_BLACK)
GRAY = (BASE_GRAY, BASE_BLACK)
DARK_GRAY = (BASE_DARK_GRAY, BASE_BLACK)
DARK = (BASE_DARK, BASE_BLACK)
DARKER = (BASE_DARKER, BASE_BLACK)
DARKEST = (BASE_DARKEST, BASE_BLACK)
DARK = (BASE_DARK, BASE_BLACK)
BLACK = (BASE_BLACK, BASE_BLACK)
