LEFT = "KEY_LEFT"
DOWN = "KEY_DOWN"
UP = "KEY_UP"
RIGHT = "KEY_RIGHT"

GROUP_YES = set("yY")
GROUP_NO = set("nN")
GROUP_ENTER = set("\r\n")
GROUP_NEUTRAL = set("zZ ")
GROUP_DEFAULT = GROUP_ENTER | GROUP_NEUTRAL
GROUP_YES_D = GROUP_YES | GROUP_DEFAULT
GROUP_NO_D = GROUP_NO | GROUP_DEFAULT
GROUP_ALL = GROUP_YES | GROUP_NO | GROUP_DEFAULT
