import curses
import const.keys as KEY

ncurses_key_map = {
    curses.ERR: KEY.NO_INPUT,
    curses.KEY_A1: KEY.NUMPAD_7,
    curses.KEY_A3: KEY.NUMPAD_9,
    curses.KEY_B2: KEY.NUMPAD_5,
    curses.KEY_BACKSPACE: KEY.BACKSPACE,
    curses.KEY_C1: KEY.NUMPAD_1,
    curses.KEY_C3: KEY.NUMPAD_3,
    curses.KEY_DC: KEY.DELETE,
    curses.KEY_DOWN: KEY.DOWN,
    curses.KEY_END: KEY.END,
    curses.KEY_F10: KEY.F10,
    curses.KEY_F11: KEY.F11,
    curses.KEY_F12: KEY.F12,
    curses.KEY_F1: KEY.F1,
    curses.KEY_F2: KEY.F2,
    curses.KEY_F3: KEY.F3,
    curses.KEY_F4: KEY.F4,
    curses.KEY_F5: KEY.F5,
    curses.KEY_F6: KEY.F6,
    curses.KEY_F7: KEY.F7,
    curses.KEY_F8: KEY.F8,
    curses.KEY_F9: KEY.F9,
    curses.KEY_FIND: KEY.NUMPAD_7,
    curses.KEY_HOME: KEY.HOME,
    curses.KEY_IC: KEY.INSERT,
    curses.KEY_LEFT: KEY.LEFT,
    curses.KEY_NPAGE: KEY.PAGE_DOWN,
    curses.KEY_PPAGE: KEY.PAGE_UP,
    curses.KEY_RESIZE: KEY.WINDOW_RESIZE,
    curses.KEY_RIGHT: KEY.RIGHT,
    curses.KEY_SELECT: KEY.NUMPAD_1,
    curses.KEY_UP: KEY.UP,
    curses.ascii.CR: KEY.ENTER,
    curses.ascii.ESC: KEY.ESC,
    curses.ascii.SP: KEY.SPACE,
    curses.ascii.TAB: KEY.TAB,
}
